### ISSUE TITLE
update user path throws exception but succeeds anyway.

### ISSUE THREAD

**Issue by ashleygould** [ucopacme/aws-orgs#68]
File "/home/agould/git-repos/github/ucopacme/aws-orgs/awsorgs/auth.py", line 174, in create_users
    user.update(NewPath=path)

**Comment by ashleygould** [comment]
```
awsorgs.utils: INFO     Updating path for user 'thanson'
Traceback (most recent call last):
  File "/home/agould/python-venv/python3.7/bin/awsauth", line 11, in <module>
    load_entry_point('aws-orgs', 'console_scripts', 'awsauth')()
  File "/home/agould/git-repos/github/ucopacme/aws-orgs/awsorgs/auth.py", line 1032, in main
    create_users(auth_credentials, args, log, deployed, auth_spec)
  File "/home/agould/git-repos/github/ucopacme/aws-orgs/awsorgs/auth.py", line 174, in create_users
    user.update(NewPath=path)
  File "/home/agould/python-venv/python3.7/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/agould/python-venv/python3.7/lib/python3.7/site-packages/boto3/resources/action.py", line 87, in __call__
    return self._response_handler(parent, params, response)
  File "/home/agould/python-venv/python3.7/lib/python3.7/site-packages/boto3/resources/response.py", line 263, in __call__
    self.service_context.service_model)
  File "/home/agould/python-venv/python3.7/lib/python3.7/site-packages/boto3/resources/response.py", line 118, in build_empty_response
    if shape.type_name == 'structure':
AttributeError: 'NoneType' object has no attribute 'type_name'

```

**Comment by ashleygould** [comment]
we think this is a boto3 bug.  no action taken.
